apiVersion: skaffold/v2beta16
kind: Config
deploy:
 helm:
   releases:
     - name: stt-proxy
       chartPath: ./infra/k8s/stt-proxy
       setValues:
        image.repository: { REPO }
        image.tag: { TAG }
        project.id: { PROJECT_ID }

        