version: "3.8"
services:
  client:
    image: stt-client:latest
    build:
      context: .
      dockerfile: ./builds/docker/Dockerfile
    volumes:
      - ./audiofiles:/audiofiles
    environment:
      # AUDIO_PATH: 'audiofiles/<file name>'
      # SERVER_ADDR: '<server IP>:8081'
      AUDIO_PATH: 'audiofiles/commercial_mono.wav'
      SERVER_ADDR: '35.204.94.32:8081'
    command: ["client"]
